---
title: "Lab5"
output: html_document
---

```{r}
setwd("D:/R for study/")
```

```{r}
#Приклад роботи функції: 
#pmean("specdata", "sulfate", 1:10) ## [1] 4.064128 pmean("specdata", "sulfate", 55) ## [1] 3.587319 pmean("specdata", "nitrate") ## [1] 1.702932
```


```{r}
pmean("specdata", "sulfate", 1:10)
```


```{r}
pmean("specdata", "sulfate", 55)
```


```{r}
pmean("specdata", "nitrate")
```

```{r}
#1)   complete("specdata", 1) ## id nobs ## 1 1 117  

#2)   complete("specdata", c(2, 4, 8, 10, 12)) ## id nobs ## 1 2 1041 ## 2           4 474 ## 3 8 192 ## 4 10 148 ## 5 12 96  
#3)   complete("specdata", 50:60) ## id nobs ## 1 50 459 ## 2 51 193 ## 3            52 812 ## 4 53 342 ## 5 54 219 ## 6 55 372 ## 7 56 642 ## 8 57               452 ## 9 58 391 ## 10 59 445 ## 11 60 448
```

```{r}
complete("specdata", 1)
```

```{r}
complete("specdata", c(2, 4, 8, 10, 12))
```

```{r}
complete("specdata", 50:60)
```

```{r}
#Приклад роботи функції: 
# cr <- corr("specdata", 150) head(cr); summary(cr) ## [1] -0.01895754 -0.14051254 -0.04389737 -0.06815956 -0.12350667 0.07588814 ## Min. 1st Qu. Median Mean 3rd Qu. Max. ## -0.21060 -0.04999 0.09463 0.12530 0.26840 0.76310  cr <- corr("specdata", 400) head(cr); summary(cr) ## [1] -0.01895754 -0.04389737 -0.06815956 -0.07588814 0.76312884 0.15782860 ## Min. 1st Qu. Median Mean 3rd Qu. Max. ## -0.17620 -0.03109 0.10020 0.13970 0.26850 0.76310  cr <- corr("specdata", 5000) head(cr); summary(cr) ; length(cr) ## NULL ## Length Class Mode ## 0 NULL NULL ## [1] 0
```


```{r}
cr <- corr("specdata", 150)
head(cr)
summary(cr)
```

```{r}
cr <- corr("specdata", 400) 
head(cr)
summary(cr)
```

```{r}
cr <- corr("specdata", 5000)
head(cr)
summary(cr)
```
